# 作業

練習以旋轉變換 + 平移變換來實現仿射變換
> 旋轉 45 度 + 縮放 0.5 倍 + 平移 (x+100, y-50)

In [1]:
import cv2
import time
import numpy as np
img = cv2.imread('lena.png')

In [2]:
"""
cos = math.cos(math.pi/4)
sin = math.sin(math.pi/4)
rotate_matrix = [[cos,-sin],[sin,cos]]
translate = np.array([[100],[-50]], dtype=np.float32)
print(translate)
"""
#取圖片的大小
rows, cols = img.shape[:2]
#旋轉矩陣 cv2.getRotationMatrix2D(中⼼位置,旋轉⾓角度,縮放倍率)
rotate_matrix = cv2.getRotationMatrix2D((cols//2, rows//2),45,0.5)
img_rotate = cv2.warpAffine(img,rotate_matrix,(cols,rows))
#平移矩陣
trans_matrix = np.array([[1,0,100],[0,1,-50]],dtype=np.float32)
img_rotate_trans = cv2.warpAffine(img_rotate,trans_matrix,(cols,rows))
# 組合 + 顯示圖片
img_show_rotate_trans = np.hstack((img, img_rotate, img_rotate_trans))
while True:
    cv2.imshow('Rotate 45, scale 0.5, Translate x+100, y-50', img_show_rotate_trans)
    k = cv2.waitKey(0)
    if k == 27:
        cv2.destroyAllWindows()
        break

## Affine Transformation - Case 2: any three point

In [3]:
# 給定兩兩一對，共三對的點
# 這邊我們先用手動設定三對點，一般情況下會有點的資料或是透過介面手動標記三個點
rows, cols = img.shape[:2]
pt1 = np.array([[50,50], [300,100], [200,300]], dtype=np.float32)
pt2 = np.array([[80,80], [330,150], [300,300]], dtype=np.float32)

# 取得 affine 矩陣並做 affine 操作
re_pt2 = np.reshape(pt2, (6,1))
print(re_pt2)
re_pt1 = np.zeros((6,6))
print(np.size(pt1))
count = 0
for i in range(np.size(pt1)):
    print(i)
    if (i%2==0):
        re_pt1[i][0]=pt1[count][0]
        re_pt1[i][1]=pt1[count][1]
        re_pt1[i][2]=1
        count = count + 1
    elif(i%2==1):
        re_pt1[i][3]=re_pt1[i-1][0]
        re_pt1[i][4]=re_pt1[i-1][1]
        re_pt1[i][5]=1
        
print(re_pt1)
M_affine = np.linalg.inv(re_pt1).dot(re_pt2)
affine = np.zeros((2,3),dtype=np.float32)
print(M_affine)
affine[0][0] = M_affine[0][0]
affine[1][0] = M_affine[1][0]
affine[0][1] = M_affine[2][0]
affine[1][1] = M_affine[3][0]
affine[0][2] = M_affine[4][0]
affine[1][2] = M_affine[5][0]
img_affine = cv2.warpAffine(img,affine,(cols,rows))
# 在圖片上標記點
img_copy = img.copy()
for idx, pts in enumerate(pt1):
    pts = tuple(map(int, pts))
    cv2.circle(img_copy, pts, 3, (0, 255, 0), -1)
    cv2.putText(img_copy, str(idx), (pts[0]+5, pts[1]+5), cv2.FONT_HERSHEY_COMPLEX, 1, (0, 255, 0), 1)

for idx, pts in enumerate(pt2):
    pts = tuple(map(int, pts))
    cv2.circle(img_affine, pts, 3, (0, 255, 0), -1)
    cv2.putText(img_affine, str(idx), (pts[0]+5, pts[1]+5), cv2.FONT_HERSHEY_COMPLEX, 1, (0, 255, 0), 1)

# 組合 + 顯示圖片
img_show_affine = np.hstack((img_copy, img_affine))
while True:
    cv2.imshow('affine transformation', img_show_affine)
    k = cv2.waitKey(0)
    if k == 27:
        cv2.destroyAllWindows()
        break

[[ 80.]
 [ 80.]
 [330.]
 [150.]
 [300.]
 [300.]]
6
0
1
2
3
4
5
[[ 50.  50.   1.   0.   0.   0.]
 [  0.   0.   0.  50.  50.   1.]
 [300. 100.   1.   0.   0.   0.]
 [  0.   0.   0. 300. 100.   1.]
 [200. 300.   1.   0.   0.   0.]
 [  0.   0.   0. 200. 300.   1.]]
[[ 0.93636364]
 [ 0.31818182]
 [17.27272727]
 [ 0.11818182]
 [ 0.80909091]
 [33.63636364]]
